[tool.pip-tools]
allow-unsafe = true
generate-hashes = true
strip-extras = true

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
select = ["B", "E4", "E5", "E7", "E9", "F", "I"]
