---
title: My Resume

sections:
  education:
    type: education

  experience:
    type: experience

  volunteering:
    type: experience

  projects:
    type: projects

  awards:
    type: awards

  skills:
    type: skills
