---
title: My Resume

settings:
  locations: false

sections:
  skills:
    type: skills

  experience:
    type: experience

  projects:
    type: projects
    omit:
      - davoxide

  volunteering:
    type: experience
    title: Leadership Experience

  education:
    type: education

  awards:
    type: awards
