---
name: Build

"on": [push]

jobs:
  discover:
    name: Discover Layouts
    runs-on: ubuntu-latest
    outputs:
      layouts: ${{ steps.discover.outputs.layouts }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - id: discover
        shell: python
        run: |
          import json
          from os import environ
          from pathlib import Path

          directory = Path.cwd() / "layouts"
          layouts = [layout.stem for layout in directory.iterdir()]

          result = json.dumps(layouts)

          if (path := environ.get("GITHUB_OUTPUT")) is not None:
            with open(path, "w") as output:
              output.write(f"layouts={result}\n")
          else:
            print(result)

  compile:
    name: Compile ${{ matrix.layout }}
    runs-on: ubuntu-latest
    needs:
      - discover
    strategy:
      fail-fast: false
      matrix:
        layout: ${{ fromJson(needs.discover.outputs.layouts)}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: ./requirements.txt

      - run: pip install -r requirements.txt
      - run: python3 site/build.py --only ${{ matrix.layout }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.layout }}.pdf
          path: build/${{ matrix.layout }}.pdf
