---
name: Publish

"on": [push]

jobs:
  select:
    name: Select
    runs-on: ubuntu-latest
    outputs:
      layouts: ${{ steps.generator.outputs.layouts }}
    steps:
      - uses: actions/checkout@v4

      - name: Find layouts
        id: generator
        run: echo "layouts=$(find ./layouts -type f -printf '"%f"\n' | jq -cs 'map(split(".") | first)')" >> "$GITHUB_OUTPUT" # yamllint disable-line rule:line-length

  compile:
    name: Compile (${{ matrix.layout }})
    runs-on: ubuntu-latest
    needs: [select]
    strategy:
      fail-fast: false
      matrix:
        layout: ${{ fromJSON(needs.select.outputs.layouts) }}
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - uses: taiki-e/install-action@just

      - run: just compile ${{ matrix.layout }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.layout }}
          path: ${{ matrix.layout }}.pdf

  compile-v2:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: ./requirements.txt

      - run: pip install -r requirements.txt
      - run: python3 scripts/build.py

      - run: ls -la build

  upload:
    name: Upload
    runs-on: ubuntu-latest
    needs: [compile]
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: publish
    steps:
      - uses: actions/download-artifact@v4

      - name: Prevent unnecessary directory nesting
        run: |
          mkdir resumes
          find . -type f -name '*.pdf' -exec mv {} resumes/ \;

      - name: aws s3 cp resumes/ s3://resumes
        run: |
          aws s3 cp resumes/ s3://resumes \
            --recursive \
            --content-disposition "inline; filename=alex-krantz-resume.pdf" \
            --content-type application/pdf \
            --metadata-directive REPLACE
        env:
          AWS_REGION: auto
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
