---
name: Publish

"on": [push]

jobs:
  select:
    name: Select
    runs-on: ubuntu-latest
    outputs:
      layouts: ${{ steps.generator.outputs.layouts }}
    steps:
      - uses: actions/checkout@v4

      - name: Find layouts
        id: generator
        run: echo "layouts=$(find ./layouts -type f -printf '"%f"' | jq -cs)" >> "$GITHUB_OUTPUT"

  compile:
    name: Compile (${{ matrix.layout }})
    runs-on: ubuntu-latest
    needs: [select]
    strategy:
      fail-fast: false
      matrix:
        layout: ${{ fromJSON(needs.select.outputs.layouts) }}
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3

      - name: typst compile main.typ
        id: compile
        run: |
          output=$(sed -e "s/yml/pdf/" -e "s/yaml/pdf/" <<< "${{ matrix.layout }}")
          typst compile main.typ $output \
            --input layout=layouts/${{ matrix.layout }} \
            --font-path ./fonts

          echo "name=$output" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.compile.outputs.name }}
          path: ${{ steps.compile.outputs.name }}

  upload:
    name: Upload
    runs-on: ubuntu-latest
    needs: [compile]
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: publish
    steps:
      - uses: actions/download-artifact@v4

      - name: Prevent unnecessary directory nesting
        run: |
          set -x
          mkdir resumes
          find . -type f -name '*.pdf' -exec mv {} resumes/ \;
          ls resumes

      - name: aws s3 cp resumes/ s3://resumes
        run: |
          aws s3 cp resumes/ s3://resumes \
            --recursive \
            --content-disposition "inline; filename=alex-krantz-resumes.pdf" \
            --content-type application/pdf \
            --metadata-directive REPLACE
        env:
          AWS_REGION: auto
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
