---
name: Publish

"on": [push]

jobs:
  select:
    name: Select
    runs-on: ubuntu-latest
    outputs:
      layouts: ${{ steps.generator.outputs.layouts }}
    steps:
      - uses: actions/checkout@v4

      - name: Find layouts
        id: generator
        run: echo "layouts=$(find ./layouts -type f -printf '"%f"' | jq -cs)" >> "$GITHUB_OUTPUT"

  compile:
    name: Compile (${{ matrix.layout }})
    runs-on: ubuntu-latest
    needs: [select]
    strategy:
      fail-fast: false
      matrix:
        layout: ${{ fromJSON(needs.select.outputs.layouts) }}
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3

      - name: typst compile main.typ
        id: compile
        run: |
          output=$(sed -e "s/yml/pdf/" -e "s/yaml/pdf/" <<< "${{ matrix.layout }}")
          typst compile main.typ $output \
            --input layout=layouts/${{ matrix.layout }} \
            --font-path ./fonts

          echo "name=$output" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.compile.outputs.name }}
          path: ${{ steps.compile.outputs.name }}
